language: r
sudo: false
cache: packages

latex: true
r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes --no-examples'

r_github_packages:
  - jimhester/covr

env:
  matrix: 
    - CXX_OLEVEL=2 CXX=clang++

before_install:
  - mkdir -p ~/.R/
  - echo "CXX = `R CMD config CXX`" >> ~/.R/Makevars
  - echo "CXXFLAGS = `R CMD config CXXFLAGS` -pedantic -g0" >> ~/.R/Makevars 
  - export CLANG_EXTRA_ARG=""
  - if [[ $CXX = "clang++" ]] ;  then export CLANG_EXTRA_ARG=" -Qunused-arguments -fcolor-diagnostics " ; fi
  - sed -i.bak "s/ g++/ ${CXX}${CLANG_EXTRA_ARG}/" ~/.R/Makevars
  - sed -i.bak "s/O[0-3]/O$CXX_OLEVEL/" ~/.R/Makevars

after_success:
- travis_wait 20 Rscript -e 'covr::codecov()'

script: 
  - |
    R CMD build . --no-build-vignettes
    travis_wait 30 R CMD check projpred_*.tar.gz --ignore-vignettes --no-examples
